[v1-0-0]
  languageName = "v1.0.x"
  contentDir = "content/v1.0.x"
  translation = true
  weight = 10
  [v1-0-0.params]
    languageISO = "ENG"
    languageTag = "en-US"
    getStartedPage = "/docs/get-started/requirements/"

[v0-6-0]
  languageName = "v0.6.x"
  contentDir = "content/v0.6.x"
  translation = true
  weight = 15
  [v0-6-0.params]
    languageISO = "ENG"
    languageTag = "en-US"
    getStartedPage = "/v0-6-0/docs/getting-started/java/"

[v1-0-0-kor]
  languageName = "v1.0.x"
  contentDir = "content/v1.0.x-kor"
  weight = 10
  translation = false
  [v1-0-0-kor.params]
    languageISO = "KOR"
    languageTag = "ko-KR"
    getStartedPage = "/docs/get-started/requirements/"

[v0-6-0-kor]
  languageName = "v0.6.x"
  contentDir = "content/v0.6.x-kor"
  weight = 15
  translation = false
  [v0-6-0-kor.params]
    languageISO = "KOR"
    languageTag = "ko-KR"
    getStartedPage = "/v0-6-0/docs/getting-started/java/"
