name: Run benchmark

on:
  push:
    branches: [ main, '[0-9]*.[0-9]*.x' ]
  pull_request:
    branches: [ main, '[0-9]*.[0-9]*.x' ]
  workflow_dispatch:

jobs:
  jmh:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute benchmark
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: jmh
      - name: Merge benchmark results
        id: merge
        run: |
          cat ./fixture-monkey/build/results/jmh/results.csv > merged_results.csv
          echo "" >> merged_results.csv
          cat ./fixture-monkey-kotlin/build/results/jmh/results.csv >> merged_results.csv
          echo "merged_results.csv content:"
          cat merged_results.csv
      - name: Read merged benchmark result
        id: csv
        uses: juliangruber/read-file-action@v1
        with:
          path: merged_results.csv
      - name: Create Markdown table
        uses: petems/csv-to-md-table-action@master
        id: csv-table-output
        with:
          csvinput: ${{ steps.csv.outputs.content }}
      - name: Print benchmark summary
        run: echo "${{steps.csv-table-output.outputs.markdown-table}}" >> $GITHUB_STEP_SUMMARY
